version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=acme
      - DOCKER_INFLUXDB_INIT_BUCKET=acme

  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    depends_on:
      - app
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    depends_on:
      - prometheus
      - influxdb
      - mailhog
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SERVER_DOMAIN=grafana
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_PROTOCOL=http

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  grafana-storage:
  influxdb-storage:
